version: "1"
services:
    web:
        build: '.'
        ports:
            -"5000:5000"
            depends_on: 
                - db
            environment:
                    -MONGO_URI = 
                